name: Django Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11.0"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Decrypt secrets.json
      run: gpg --quiet --batch --yes --decrypt --passphrase="$PASS_PHRASE" --output $HOME/secrets.json secrets.json.gpg
      env:
        PASS_PHRASE: ${{ secrets.PASS_PHRASE }}

    - name: Move secrets.json
      run: mv $HOME/secrets.json /home/runner/work/GaGgaMaGga_BE/GaGgaMaGga_BE

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run User App Tests
      run: |
        python manage.py test users

    - name: Run Place App Tests
      run: |
        python manage.py test places

    - name: Run Review App Tests
      run: |
        python manage.py test reviews

    - name: Run Notification App Tests
      run: |
        python manage.py test notification
